In [1]:
import numpy as np
# Membuat matrik 3x3
matrix=np.array([[1,4,6],[2,5,2],[6,-4,-7]])
matrix

array([[ 1,  4,  6],
       [ 2,  5,  2],
       [ 6, -4, -7]])

In [2]:
# mencari nilai inverse matrik tersebut
np.linalg.inv(matrix)

array([[ 0.17880795, -0.02649007,  0.14569536],
       [-0.17218543,  0.28476821, -0.06622517],
       [ 0.25165563, -0.18543046,  0.01986755]])

In [1]:
import lightgbm as lgb

In [4]:
# 1. Bilangan Bulat (integer)
a=12
# 2. Boolean
b= False
c= True
# 3. Bilangan Pecahan (Real/float)
d=12.5
# 4. Bilangan kompleks
x=complex(5,6)
y=complex(7,8)
e=x+y
print(8*'='+'Tipe Data Numerik'+8*'=')
print('contoh tipe data bilangan bulat =', a, type(a))
print('contoh tipe data bilangan bulat =', b, type(b))
print('contoh tipe data bilangan pecahan =', d, type(d))
print('contoh tipe data bilangan complex =', e, type(e))

========Tipe Data Numerik========
contoh tipe data bilangan bulat = 12 <class 'int'>
contoh tipe data bilangan bulat = False <class 'bool'>
contoh tipe data bilangan pecahan = 12.5 <class 'float'>
contoh tipe data bilangan complex = (12+14j) <class 'complex'>


In [5]:
import pandas as pd

df = pd.DataFrame({
    'tanggal_mulai':['2021-01-01', '2021-01-02', '2021-01-03'],
    'tanggal_selesai':['2022-02-02', '2021-02-02', '2021-03-03'],
    'kode_pekerjaan':[1,2,'tiga'],
    'jenis_kelas':['class-1', 'class-2', 'class-1']
})

df['tanggal_mulai'] = pd.to_datetime(df['tanggal_mulai'])
df['tanggal_selesai'] = pd.to_datetime(df['tanggal_selesai'])
df['durasi'] = df['tanggal_selesai'] - df['tanggal_mulai']
df['jenis_kelas'] = df['jenis_kelas'].astype('category')
df

tanggal_mulai tanggal_selesai kode_pekerjaan jenis_kelas   durasi
0    2021-01-01      2022-02-02              1     class-1 397 days
1    2021-01-02      2021-02-02              2     class-2  31 days
2    2021-01-03      2021-03-03           tiga     class-1  59 days

In [6]:
df.dtypes

tanggal_mulai       datetime64[ns]
tanggal_selesai     datetime64[ns]
kode_pekerjaan              object
jenis_kelas               category
durasi             timedelta64[ns]
dtype: object

In [7]:
# 1. string
# Membuat data string
print("###############################################")
print("----------------Manipulasi String--------------")
print("---------------Created: Dzaya 2022-------------")
print("\n########## Menggabungkan String ###########\n")
#menggabungkan String (Concate)
F_name=input('Masukan Nama Depan :')
M_name=input('Masukan Nama Tengah :')
L_name=input('Masukan Nama Belakang :')
spasi=(' ')
full_name=F_name+spasi+M_name+spasi+L_name
print('nama lengkap anda =',full_name)

###############################################
----------------Manipulasi String--------------
---------------Created: Dzaya 2022-------------

########## Menggabungkan String ###########

Masukan Nama Depan :Budi
Masukan Nama Tengah :Nur
Masukan Nama Belakang :Cahyono
nama lengkap anda = Budi Nur Cahyono


In [2]:
print("\n########## Melihat Panjang String #########\n")
panjang=len(full_name)
kar=F_name+M_name+L_name
J_kar=len(kar)
print('panjang string didalam nama lengkap anda =',panjang)
print('jumlah huruf didalam nama lengkap anda =',J_kar)
a=input('\nmasukan huruf yang ingin diketahui jumlahnya =')
jml=full_name.count(a)
print('jumlah huruf ',a,' didalam nama lengkap anda =',jml)


########## Melihat Panjang String #########



NameError: name 'full_name' is not defined

In [9]:
print("\n################# Indexing ################\n")
print('Urutan ke 0 =', full_name[0])
print('Urutan ke 1 =', full_name[1])
print('Urutan ke 2 =', full_name[2])
print('Urutan ke 3 =', full_name[3])
print('Urutan ke 4 =', full_name[4])
print('Urutan ke 5 =', full_name[5])
print('Urutan ke 6 =', full_name[6])
print('Urutan ke 7 =', full_name[7])
urut=input('\nmasukan no .urutan huruf yang ingin diketahui =')
x=int(urut)
y=full_name[x]
print('Urutan ke ',urut +' adalah karakter: '+ y)


################# Indexing ################

Urutan ke 0 = B
Urutan ke 1 = u
Urutan ke 2 = d
Urutan ke 3 = i
Urutan ke 4 =  
Urutan ke 5 = N
Urutan ke 6 = u
Urutan ke 7 = r

masukan no .urutan huruf yang ingin diketahui =5
Urutan ke  5 adalah karakter: N


In [10]:
print("\n################# Mengubah Bentuk ################\n")
ascii_code=ord(y)
print('bentuk ascii dari karakter',y,' adalah: ',ascii_code)
z=chr(ascii_code)
print('bentuk karakter dari ascii code',ascii_code,' adalah: ',z)


################# Mengubah Bentuk ################

bentuk ascii dari karakter N  adalah:  78
bentuk karakter dari ascii code 78  adalah:  N


In [11]:
# membuat tuple
tuple1 = ( 'Raffanda', 'ELzio', 'Dzaya', 'Kanaya', 'Adiva' )
tuple2 = (123, 2016, 2022)
print (10*'#'+'AKSES, INDEX dan SLICING DATA TUPEL'+10*'#'+'\n')
print (f"contoh tupel =\n{tuple1},\n {tuple2}")
# indexing tuple elemen pertama pada tuple
print (tuple1[0])
# slicing data dari elemen kedua sampai ketiga
print (tuple1[1:3])
# slicing data dimulai dari elemen ketiga
print (tuple2[2:])

##########AKSES, INDEX dan SLICING DATA TUPEL##########

contoh tupel =
('Raffanda', 'ELzio', 'Dzaya', 'Kanaya', 'Adiva'),
 (123, 2016, 2022)
Raffanda
('ELzio', 'Dzaya')
(2022,)


In [12]:
# Menggabungkan tuple1 dengan tuple2
tuple3= (tuple1+tuple2)
print (10*'#'+'UPDATE/MENGABUNGKAN TUPEL'+10*'#')
print (f"tupel 1 dengan tipe data string = {tuple1}")
print (f"tupel 2 dengan tipe data numerik = {tuple2}")
print (f"hasil gabungan tupel 1 & 2 = {tuple3}")

##########UPDATE/MENGABUNGKAN TUPEL##########
tupel 1 dengan tipe data string = ('Raffanda', 'ELzio', 'Dzaya', 'Kanaya', 'Adiva')
tupel 2 dengan tipe data numerik = (123, 2016, 2022)
hasil gabungan tupel 1 & 2 = ('Raffanda', 'ELzio', 'Dzaya', 'Kanaya', 'Adiva', 123, 2016, 2022)


In [13]:
print (10*'#'+' MENGHAPUS DATA TUPEL '+10*'#'+'\n')
print("menampilkan data tuple : ",tuple3)
del(tuple3)

########## MENGHAPUS DATA TUPEL ##########

menampilkan data tuple :  ('Raffanda', 'ELzio', 'Dzaya', 'Kanaya', 'Adiva', 123, 2016, 2022)


In [14]:
# Membuat List
listStr=['nama','alamat','usia']
listNum=[4,5,6,7,8]

print(8*'='+'Mutable Sequences'+8*'=')
print('contoh tipe data List =', listStr, type(listStr))
print('\n', 5*'#'+' INDEXING PADA LIST'+ 5*'#')
print(listStr)
print(f"menampilkan nilai indexing 2 listStr = {listStr[2]}")
print(f"menampilkan nilai indexing -2 listStr = {listStr[-2]}")

========Mutable Sequences========
contoh tipe data List = ['nama', 'alamat', 'usia'] <class 'list'>

 ##### INDEXING PADA LIST#####
['nama', 'alamat', 'usia']
menampilkan nilai indexing 2 listStr = usia
menampilkan nilai indexing -2 listStr = alamat


In [15]:
# Membuat List
listStr=['Budi','Jl.Baru','25']
listNum=[4,5,6,7,8]

print(8*'='+'Mutable Sequences'+8*'=')
print('contoh tipe data List =', listStr, type(listStr))
print('\n', 5*'#'+' INDEXING PADA LIST'+ 5*'#')
print(listStr)
print(f"menampilkan nilai indexing 2 listStr = {listStr[2]}")
print(f"menampilkan nilai indexing -2 listStr = {listStr[-2]}")

========Mutable Sequences========
contoh tipe data List = ['Budi', 'Jl.Baru', '25'] <class 'list'>

 ##### INDEXING PADA LIST#####
['Budi', 'Jl.Baru', '25']
menampilkan nilai indexing 2 listStr = 25
menampilkan nilai indexing -2 listStr = Jl.Baru


In [16]:
print('\n', 5*'#'+' TAMBAH ELEMEN NILAI PADA LIST'+ 5*'#')
print(f"menampilkan elemen nilai didalam list = {listNum}")
listNum=listNum+['nilai']
print(f"elemen nilai list setelah ditambahkan = {listNum}")
listStr.append('fungsi append')
print(f"elemen nilai list setelah ditambahkan = {listStr}")


 ##### TAMBAH ELEMEN NILAI PADA LIST#####
menampilkan elemen nilai didalam list = [4, 5, 6, 7, 8]
elemen nilai list setelah ditambahkan = [4, 5, 6, 7, 8, 'nilai']
elemen nilai list setelah ditambahkan = ['Budi', 'Jl.Baru', '25', 'fungsi append']


In [17]:
print('\n', 5*'#'+' MENGUBAH ELEMEN NILAI PADA LIST'+ 5*'#')
print(f"menampilkan elemen nilai didalam list = {listNum}")
listNum[4]='update nilai'
print(f"menampilkan seluruh elemen nilai pada list setelah ditambahkan dan di update = {listNum}")


 ##### MENGUBAH ELEMEN NILAI PADA LIST#####
menampilkan elemen nilai didalam list = [4, 5, 6, 7, 8, 'nilai']
menampilkan seluruh elemen nilai pada list setelah ditambahkan dan di update = [4, 5, 6, 7, 'update nilai', 'nilai']


In [18]:
print('\n', 5*'#'+'MENGHAPUS ELEMEN NILAI PADA LIST'+ 5*'#')
print(f"nilai awal pada list = {listNum}")
# menghapus data list berdasarkan pada indexing
del listNum[3]
print(f"nilai pada list setelah index ke 3 dihapus (del) = {listNum}")
# menghapus data list berdasarkan pada secara langsung
listNum.remove(4)
listNum.remove('update nilai')
print(f"nilai pada list setelah nilai 4 dan update nilai dihapus (remove) = {listNum}")


 #####MENGHAPUS ELEMEN NILAI PADA LIST#####
nilai awal pada list = [4, 5, 6, 7, 'update nilai', 'nilai']
nilai pada list setelah index ke 3 dihapus (del) = [4, 5, 6, 'update nilai', 'nilai']
nilai pada list setelah nilai 4 dan update nilai dihapus (remove) = [5, 6, 'nilai']


In [19]:
import numpy as np
array1=np.array([4,5,6,7,8,9,10])
array1

array([ 4,  5,  6,  7,  8,  9, 10])

In [20]:
array1/2

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [21]:
matriks1=np.array([[3,7,8],[2,3,4],[3,4,5]])
matriks1

array([[3, 7, 8],
       [2, 3, 4],
       [3, 4, 5]])

In [22]:
np.linalg.inv(matriks1)

array([[-0.33333333, -1.        ,  1.33333333],
       [ 0.66666667, -3.        ,  1.33333333],
       [-0.33333333,  3.        , -1.66666667]])

In [23]:
from sys import getsizeof
cektuple=(3,7,8)
ceklist=[3,7,8]
ceknumpy=([3,7,8])
print(getsizeof(cektuple))
print(getsizeof(ceklist))
print(getsizeof(ceknumpy))

64
88
88


In [24]:
print(5*"#"+" TIPE DATA SET "+5*"#")
# data set dengan tipe string
string_set = { "Eric", "Ali", "John" }
#data set dengan tipe numerik
num_set={ 1, 2,3 }
print(string_set)
print(num_set)
#menambahkan data set
tambah_numset=int(input('masukan tipe data set numerik ='))
string_set.add(tambah_numset)
print(f"isi data set setelah ditambahkan data adalah = {string_set}")

##### TIPE DATA SET #####
{'Ali', 'John', 'Eric'}
{1, 2, 3}
masukan tipe data set numerik =2
isi data set setelah ditambahkan data adalah = {'Ali', 2, 'John', 'Eric'}


In [25]:
print("\n"+5*"#"+" KONVERSI DATA/OBJEK LAIN MENJADI DATA SET "+5*"#"+"\n")
dtString=input('masukan nama anda = ')
dt1=int(input('masukan tanggal lahir anda = '))
dt2=int(input('masukan bulan lahir anda = '))
dt3=int(input('masukan tahun lahir anda = '))
x=set(dtString)
y=set([dt1,dt2,dt3])
print(f"nama anda di konversi menjadi data set = {x}")
print(f"nama anda di konversi menjadi data set = {y}")


##### KONVERSI DATA/OBJEK LAIN MENJADI DATA SET #####

masukan nama anda = Budi Nurcahyono
masukan tanggal lahir anda = 22
masukan bulan lahir anda = 11
masukan tahun lahir anda = 1999
nama anda di konversi menjadi data set = {'n', 'i', 'r', 'N', ' ', 'y', 'a', 'c', 'h', 'o', 'u', 'd', 'B'}
nama anda di konversi menjadi data set = {11, 22, 1999}


In [26]:
print("\n"+5*"#"+" KONVERSI TIPE DATA LIST KE DATA SET "+5*"#"+"\n")
mylist=["senin", 1, "selasa", 2, "rabu", 2, "kamis", 4,"senin", 4]
print(f"contoh data list = {mylist}")
myset=set(mylist)
print(f"hasil konversi data list menjadi data set = {myset}")
print("\n"+5*"#"+" KONVERSI TIPE DATA SET KE DATA LIST "+5*"#"+"\n")
print(f"contoh data set = {myset}")
con_list=list(myset)
print(f"hasil konversi data set menjadi data list = {con_list}")


##### KONVERSI TIPE DATA LIST KE DATA SET #####

contoh data list = ['senin', 1, 'selasa', 2, 'rabu', 2, 'kamis', 4, 'senin', 4]
hasil konversi data list menjadi data set = {1, 'senin', 2, 4, 'rabu', 'selasa', 'kamis'}

##### KONVERSI TIPE DATA SET KE DATA LIST #####

contoh data set = {1, 'senin', 2, 4, 'rabu', 'selasa', 'kamis'}
hasil konversi data set menjadi data list = [1, 'senin', 2, 4, 'rabu', 'selasa', 'kamis']


In [27]:
# Membuat Tipe Data Dictionary
kamuskosong={}
kamus1={'k1':"kunci 1",'k2':"kunci2",'k3':123}
print(5*"#"+"TIPE DATA DICTIONARY "+5*"#"+"\n")
print("membuat sebuah kamus kosong ="+ "\n",(kamuskosong))
print("ini adalah bentuk dasar penulisan kamus ="+"\n",(kamus1))
print("ini adalah kunci pada kamus1 ="+"\n",(kamus1.keys()))
print(f"ini adalah item nilai pada kamus1 ="+"\n",(kamus1.values()))

#####TIPE DATA DICTIONARY #####

membuat sebuah kamus kosong =
 {}
ini adalah bentuk dasar penulisan kamus =
 {'k1': 'kunci 1', 'k2': 'kunci2', 'k3': 123}
ini adalah kunci pada kamus1 =
 dict_keys(['k1', 'k2', 'k3'])
ini adalah item nilai pada kamus1 =
 dict_values(['kunci 1', 'kunci2', 123])


In [28]:
dic1={"nama":"elzio","usia":'6 tahun','alamat':'tangerang'}
dic2={1:"Raffanda",2:'Elzio',3:'Jaya'}
print(10*"#"+"MENGAKSES DICTIONARY"+10*"#")
print("ini adalah contoh tipe data dictionary"+"\n",(dic1))
print((dic1['nama']))
print((dic1['usia']))
print((dic1['alamat']))
print(dic2[1])

##########MENGAKSES DICTIONARY##########
ini adalah contoh tipe data dictionary
 {'nama': 'elzio', 'usia': '6 tahun', 'alamat': 'tangerang'}
elzio
6 tahun
tangerang
Raffanda


In [29]:
print(10*"#"+"MENAMBAH & UPDATE DICTIONARY"+10*"#")
print("data dictionary awal"+"\n",(dic1))
# update item nilai usia
dic1['usia'] ="8 tahun"; 
print("data dictionary setelah di update"+"\n",(dic1))
# menambahkan pasangan kunci dan nilai baru
dic1['Jenis_Kelamin'] = "Laki-Laki" 
print("data dictionary setelah di tambahkan"+"\n",(dic1))

##########MENAMBAH & UPDATE DICTIONARY##########
data dictionary awal
 {'nama': 'elzio', 'usia': '6 tahun', 'alamat': 'tangerang'}
data dictionary setelah di update
 {'nama': 'elzio', 'usia': '8 tahun', 'alamat': 'tangerang'}
data dictionary setelah di tambahkan
 {'nama': 'elzio', 'usia': '8 tahun', 'alamat': 'tangerang', 'Jenis_Kelamin': 'Laki-Laki'}


In [30]:
print(10*"#"+"MENGHAPUS DATA DICTIONARY"+10*"#")
print(f"data awal dictionary ={dic1}")
del dic1['alamat'] # menhapus data dengan key 'alamat'
print(f"data dictionary setelah alamat dihapus ={dic1}")
# menghapus semua nilai didalam dictionary
dic1.clear()
print(f"data dictionary setelah semua nilai dihapus ={dic1}")
# menghapus data dictionary
del dic1
print(f"setelah data dictionary dihapus ={dic1}")

##########MENGHAPUS DATA DICTIONARY##########
data awal dictionary ={'nama': 'elzio', 'usia': '8 tahun', 'alamat': 'tangerang', 'Jenis_Kelamin': 'Laki-Laki'}
data dictionary setelah alamat dihapus ={'nama': 'elzio', 'usia': '8 tahun', 'Jenis_Kelamin': 'Laki-Laki'}
data dictionary setelah semua nilai dihapus ={}


NameError: name 'dic1' is not defined

In [31]:
print('******** OPERATOR ASSIGNMENT *******\n')
a=7
b=2
c=a+b
print('nilai a = ',a)
print('nilai b = ',b)
print('nilai c hasil dari nilai a ditambahkan dengan nilai b = ',c)
c+=a
print('nilai c ditambahkan dengan nilai a = ',c)
c-=a
print('nilai c dikurangi dengan nilai a = ',c)
c*=b
print('nilai c dikali dengan nilai b = ',c)
a/=b
print('nilai a dibagi dengan nilai b = ',a)
a//=b
print('nilai a dibagi dengan nilai b = ',a)
c**=b
print('nilai c dipangkatkan dengan nilai b = ',c)
c%=b
print('nilai a modulus dari nilai b = ',c)

******** OPERATOR ASSIGNMENT *******

nilai a =  7
nilai b =  2
nilai c hasil dari nilai a ditambahkan dengan nilai b =  9
nilai c ditambahkan dengan nilai a =  16
nilai c dikurangi dengan nilai a =  9
nilai c dikali dengan nilai b =  18
nilai a dibagi dengan nilai b =  3.5
nilai a dibagi dengan nilai b =  1.0
nilai c dipangkatkan dengan nilai b =  324
nilai a modulus dari nilai b =  0


In [32]:
print ('******* OPERATOR ARITMATIKA ********')
a1= 3+5 
print('hasil dari operator penjumlahan = ',a1)
b1= 8-1
print('hasil dari operator Pengurangan = ',b1)
c1=7/3 
print('hasil dari operator Pembagian bilangan float = ', c1)
d1=7//3 
print('hasil dari operator Pembagian bilangan int = ', d1)
e1= 7%3 
print('hasil darioperator modulus',e1)
f1= 3**3 
print('hasil dari operator pemangkatan',f1)

******* OPERATOR ARITMATIKA ********
hasil dari operator penjumlahan =  8
hasil dari operator Pengurangan =  7
hasil dari operator Pembagian bilangan float =  2.3333333333333335
hasil dari operator Pembagian bilangan int =  2
hasil darioperator modulus 1
hasil dari operator pemangkatan 27


In [33]:
a=(input('masukan angka pertama ='))
b=(input('masukan angka kedua ='))
print('apakah nilai pertama sama dengan nilai kedua ?')
print(a==b)
print('apakah nilai pertama tidak sama dengan nilai kedua ?')
print(a!=b)
print('apakah nilai pertama lebih besar dari nilai kedua ?')
print(a>b)
print('apakah nilai pertama lebih kecil dari nilai kedua ?')
print(a<b)
print('apakah nilai pertama lebih besar sama dengan nilai kedua ?')
print(a>=b)
print('apakah nilai pertama lebih kecil sama dengan nilai kedua ?')
print(a<=b)

masukan angka pertama =2
masukan angka kedua =4
apakah nilai pertama sama dengan nilai kedua ?
False
apakah nilai pertama tidak sama dengan nilai kedua ?
True
apakah nilai pertama lebih besar dari nilai kedua ?
False
apakah nilai pertama lebih kecil dari nilai kedua ?
True
apakah nilai pertama lebih besar sama dengan nilai kedua ?
False
apakah nilai pertama lebih kecil sama dengan nilai kedua ?
True


In [34]:
print('\n########### OPERATOR LOGIKA ###########')
a=True
b=False
c=True
a1=1
b1=2
c1=3
print('#######AND########\n')
print('bernilai TRUE jika kedua nilai variabel=TRUE')
print('nilai a dan b =',a and b)
print('apakah nilai b1 lebih kecil dari a1 dan nilai c1 lebih kecil dari a1 =',(b1<a1) and (c1<a1))
print('nilai a dan b =',a and b)
print('apakah nilai b1 lebih kecil dari a1 dan nilai a1 lebih dari c1 =',(b1<a1) and (a1<c1))
print('nilai a dan c =',a and c)
print('apakah nilai a1 lebih kecil dari b1 dan nilai a1 lebih dari b1 =',(a1<b1) and (a1<c1))
print('\n#######OR########\n')
print('bernilai TRUE jika salah satu dari kedua nilai variabel=TRUE')
print('nilai a atau b =',a or b)
print('\n#######NOT########\n')
print('bernilai TRUE jika nilai sebuah variabel=FALSE')
print('nilai a  =',not a)
print('nilai a1 tidak lebih besar dari b1=', not(a1>b1))
print('nilai b  =',not b)


########### OPERATOR LOGIKA ###########
#######AND########

bernilai TRUE jika kedua nilai variabel=TRUE
nilai a dan b = False
apakah nilai b1 lebih kecil dari a1 dan nilai c1 lebih kecil dari a1 = False
nilai a dan b = False
apakah nilai b1 lebih kecil dari a1 dan nilai a1 lebih dari c1 = False
nilai a dan c = True
apakah nilai a1 lebih kecil dari b1 dan nilai a1 lebih dari b1 = True

#######OR########

bernilai TRUE jika salah satu dari kedua nilai variabel=TRUE
nilai a atau b = True

#######NOT########

bernilai TRUE jika nilai sebuah variabel=FALSE
nilai a  = False
nilai a1 tidak lebih besar dari b1= True
nilai b  = True


In [35]:
a = 60 # 60 = 0011 1100
b = 13 # 13 = 0000 1101
print("\n################### BITWISE AND (&) ############################")
c = a & b; # 12 = 0000 1100
print ("jika nilai a dan b =TRUE(1), hasilnya adalah TRUE (1)")
print ("Nilai dari a =", a,' binary :',format(a,'08b'))
print ("Nilai dari b =", b,' binary :',format(b,'08b'))
print ("Nilai dari a =", c,' binary :',format(c,'08b'))
print('\n################### BITWISE OR (|) #############################')
c = a | b; # 61 = 0011 1101
print ("jika kedua nilai atau salah satu nilai dari a dan b =TRUE(1), hasilnya adalah TRUE (1)")
print ("Nilai dari a =", a,' binary :',format(a,'08b'))
print ("Nilai dari b =", b,' binary :',format(b,'08b'))
print ("Nilai dari c =", c,' binary :',format(c,'08b'))
print('\n############### BITWISE XOR (^) ################################')
c = a ^ b; # 49 = 0011 0001
print ("jika salah satu nilai dari a dan b =TRUE(1), hasilnya adalah TRUE (1)")
print ("Nilai dari a =", a,' binary :',format(a,'08b'))
print ("Nilai dari b =", b,' binary :',format(b,'08b'))
print ("Nilai dari a =", c,' binary :',format(c,'08b'))
print('\n################ BITWISE NOT (~) ###############################')
x = 0
y=~x; 
x1=~b;
print ("Operator biner Negative, membalik nilai bit. Misal dari 1 menjadi 0")
print ("Nilai dari x =", x,' binary :',format(x,'08b'))
print ("Nilai dari -x =", y,' binary :',format(y,'08b'))
print ("Nilai dari b =", b,' binary :',format(b,'08b'))
print ("Nilai dari -b =", x1,' binary :',format(x1,'08b'))
print('\n################ BITWISE SHIFT LEFT (<<) ######################')
c = a << 2; # 240 = 1111 0000
print ("menggeser nilai kekiri bit sebanyak n kali")
print ("Nilai dari a =", a,' binary :',format(a,'08b'))
print ("menggeser bit Nilai dari a sebanyak 2 kali =", c,' binary :',format(c,'08b'))
print('\n################# BITWISE SHIFT RIGHT(>>) ######################')
c = a >> 2; # 15 = 0000 1111
print ("menggeser nilai kekanan bit sebanyak n kali")
print ("Nilai dari a =", a,' binary :',format(a,'08b'))
print ("menggeser bit Nilai dari a kekanan 2 kali =", c,' binary :',format(c,'08b'))


################### BITWISE AND (&) ############################
jika nilai a dan b =TRUE(1), hasilnya adalah TRUE (1)
Nilai dari a = 60  binary : 00111100
Nilai dari b = 13  binary : 00001101
Nilai dari a = 12  binary : 00001100

################### BITWISE OR (|) #############################
jika kedua nilai atau salah satu nilai dari a dan b =TRUE(1), hasilnya adalah TRUE (1)
Nilai dari a = 60  binary : 00111100
Nilai dari b = 13  binary : 00001101
Nilai dari c = 61  binary : 00111101

############### BITWISE XOR (^) ################################
jika salah satu nilai dari a dan b =TRUE(1), hasilnya adalah TRUE (1)
Nilai dari a = 60  binary : 00111100
Nilai dari b = 13  binary : 00001101
Nilai dari a = 49  binary : 00110001

################ BITWISE NOT (~) ###############################
Operator biner Negative, membalik nilai bit. Misal dari 1 menjadi 0
Nilai dari x = 0  binary : 00000000
Nilai dari -x = -1  binary : -0000001
Nilai dari b = 13  binary : 00001101
Nilai dari -b

In [36]:
fruits = {"apple", "banana", "tomato"}
veggies = {"eggplant", "tomato"}
print(fruits | veggies)
print(fruits & veggies)
print(fruits ^ veggies)

{'banana', 'eggplant', 'tomato', 'apple'}
{'tomato'}
{'eggplant', 'banana', 'apple'}


In [37]:
x_list=[1, 3, 5, 7, 9]
y_tuple=('N', 'E', 'T', 'I', 'N', 'D', 'O')
print('\n######## Operator in #######')
print('bernilai TRUE jika sebuah nilai terdapat didalam list')
print( 'nilai 5 ada didalam X list = ',5 in x_list)
print( 'nilai 12 ada didalam X list = ', 12 in x_list)
print('\n######## Operator not in #######')
print('bernilai TRUE jika sebuah nilai tidak terdapat didalam list')
print( 'huruf A tidak ada didalam Y tuple = ', 'A' not in y_tuple)
print( 'huruf N tidak ada didalam Y tuple = ', 'N'  not in y_tuple)


######## Operator in #######
bernilai TRUE jika sebuah nilai terdapat didalam list
nilai 5 ada didalam X list =  True
nilai 12 ada didalam X list =  False

######## Operator not in #######
bernilai TRUE jika sebuah nilai tidak terdapat didalam list
huruf A tidak ada didalam Y tuple =  True
huruf N tidak ada didalam Y tuple =  False
